Env rewards2
Toroi01/TradingRLBot pull request #23
Opened 2021-06-20 18:27 UTC by ElenaBonan

Added some other rewards type and and some old code in case it can be useful

2021-06-22 16:41 UTC, dvdpedros requested changes, later dismissed

2021-06-22 16:41 UTC, dvdpedros commented on config/config.py
> +TECHNICAL_INDICATORS_LIST2 = ['psar', 'ui', 'atr', 'bbw', 'bbp', 'bbhi', 'bbli','kcp', 'kchi','kcli', 'macd', 'macd_diff', 'mass_index', 'dpo', 'kst','aroon_up', 'aroon_down','ppo']
Hola! Yo los añadiría al principal (TECHNICAL_INDICATORS_LIST), que te parece?

2021-06-22 16:41 UTC, dvdpedros commented on env/env_custom.py
> +        reward = self._compute_reward(prev_portfolio_value, new_portfolio_value, self.reward_type, new_hourly_data)
El reward no hace falta pasarlo por parámetro realmente

2021-06-22 16:41 UTC, dvdpedros commented on env/env_custom.py
> +            if future_window >0:
No sé si lo he entendido bien, pero creo que nunca va a ser mayor de 0 no?  Si haces el min(0, cualquier cosa), el resultado siempre va a ser 0 o menor

2021-06-22 16:41 UTC, dvdpedros commented on env/env_custom.py
> +            if df_historic.shape[0] < 3:
A que se refiere este 3?

2021-06-22 17:01 UTC, ElenaBonan commented on config/config.py
> +TECHNICAL_INDICATORS_LIST2 = ['psar', 'ui', 'atr', 'bbw', 'bbp', 'bbhi', 'bbli','kcp', 'kchi','kcli', 'macd', 'macd_diff', 'mass_index', 'dpo', 'kst','aroon_up', 'aroon_down','ppo']
Si me gustaria pero tengo que hacer la prueba final que funciona con los ultimos cambios en el codigo. EL jueves puedo testearlo mas.

2021-06-22 17:03 UTC, ElenaBonan commented on env/env_custom.py
> +        reward = self._compute_reward(prev_portfolio_value, new_portfolio_value, self.reward_type, new_hourly_data)
porque (curiosidad)? Creia que era mas claro, pero si ves que no tiene sentido por como se estructure el codigo normalmente lo quito

2021-06-22 17:05 UTC, ElenaBonan commented on env/env_custom.py
> +            if future_window >0:
Este es lo que me daba el problema, el error lo tenia cuando future window estaba > 0. Entonces por ahora he puesto 0.
 Siempre el jueves lo queria arreglar.

2021-06-22 17:06 UTC, ElenaBonan commented on env/env_custom.py
> +            if df_historic.shape[0] < 3:
Por cualcular el sharpe ratio tengo tener por lo menos 3 values. 
Esta parte no esta muy esplicata pero queria ver antes que funciona despues puedo definir una funciones

2021-06-22 17:17 UTC, dvdpedros commented on env/env_custom.py
> +        reward = self._compute_reward(prev_portfolio_value, new_portfolio_value, self.reward_type, new_hourly_data)
Normalmente los parámetros que se le pasan a los métodos de una clase no incluyen los atributos que ya tiene la clase. 
Realmente tu código funciona igual, pero como no es necesario puede ser confuso. Por ejemplo, podría pasar que alguien cambie el reward_type dentro de la función _compute_reward sin enterarse que realmente esta cambiando el atributo de la clase.

2021-06-22 17:17 UTC, dvdpedros commented on env/env_custom.py
> +            if df_historic.shape[0] < 3:
Vale! Si puedes añadir un comentario seria perfecto.

2021-06-22 17:18 UTC, dvdpedros commented on env/env_custom.py
> +            if future_window >0:
Si puedes añadir un TODO seria perfecto

2021-06-26 16:41 UTC, dvdpedros commented on preprocessing/preprocessors.py
> +            df = self.add_indicators(df)
Si esta es la nueva manera de añadir los indicadores seria mejor borrar la función `add_technical_indicator `, ya que no se utilizará en ningún sitio no?

2021-06-26 16:42 UTC, dvdpedros commented on preprocessing/preprocessors.py
> +def add_covariance(df , lookback):
Dónde se utiliza esta función?

2021-06-27 10:06 UTC, ElenaBonan commented on preprocessing/preprocessors.py
> +            df = self.add_indicators(df)
prefiero tenerla hasta que comprobamos que todo funciona bien despues antes de presentarlo eliminamos todo el codigo que no se utiliza.

2021-06-27 10:09 UTC, ElenaBonan commented on preprocessing/preprocessors.py
> +def add_covariance(df , lookback):
En el main para poner la covariancia. Pero al final me parece que no la ponemos la utilizamo la covariancia en el environmenr entonces no he cambiado el main.

2021-06-27 15:58 UTC, merged